### ISSUE TITLE
Contracts support

### ISSUE THREAD

**Issue by marc0olo** [kryptokrauts/aepp-sdk-java#10]
- https://github.com/aeternity/protocol/blob/master/serializations.md#contract

**Comment by mj-ampnet** [comment]
Hi! We are planning on using your SDK on our Kotlin backend. Contract support is very important to us - if there is any way we can help, ping me!

**Comment by mitch-lbw** [comment]
Hi Mislav, 
thanks for your offer of helping :) - contract support will be one of the very next features we're planning to realize. As soon it is implemented we will provide it in the snapshot .

**Comment by mj-ampnet** [comment]
Excellent, thank you! We're planning on building a higher-level framework on top of this for things such as QR code generation, offline signing, etc... Looking forward to the snapshot.

**Comment by marc0olo** [comment]
We also have plans to provide a gradle plugin that generates classes for your smart contracts so that you don't have to write the boilerplate code by yourself. The SDK services will automatically be included in these classes.

**Comment by marc0olo** [comment]
Example contracts:
- https://github.com/aeternity/aepp-sophia-examples

Online-tool to compile and get the bytecode:
- https://testnet.contracts.aepps.com/

**Comment by mj-ampnet** [comment]
Thanks for the updates! You've saved us quite a bit of precious time :)

**Comment by mj-ampnet** [comment]
A thread I made on the Aeternity forum might be of some assistance to the development of contract support
https://forum.aeternity.com/t/building-and-signing-raw-transactions/2798/2

**Comment by marc0olo** [comment]
> Thanks for the updates! You've saved us quite a bit of precious time :)

glad to hear that. we appreciate when projects are interested in using our SDK 😃

**Comment by mitch-lbw** [comment]
Further discussion on contractCreateTx on ae-forum
https://forum.aeternity.com/t/creation-of-contracttx-java-sdk/3083

**Comment by marc0olo** [comment]
We are at final stage for contract-support now.

Tasks done:
- [x] added CompilerService to compile smart contracts written in Sophia
- [x] support CreateContractTx
- [x] support CallContractTx
- [x] automatically calculate required fee (can be set manually if wanted)

Tasks open:
- [ ] estimate gas and gasPrice for Contract calls (dryRun)
  - some open questions here
- [ ] support listening to chain-events (if possible without middleware)

**Comment by mitch-lbw** [comment]
Hi @mj-ampnet ,
you can now use the snapshot dependency to test contract creation and contract call. This would be nice to get some insights about possible issues :)
Thx for using our SDK and greets,
Mitch

**Comment by marc0olo** [comment]
for decoding results it is currently needed to make use of the sophia compiler. it is planned to provide an more comfortable way in the future.

chain-events are currently out of scope. we will focus on that later
