### ISSUE TITLE
disable vert.x cache folder to be created by default

### ISSUE THREAD

**Issue by marc0olo** [kryptokrauts/aepp-sdk-java#123]
when developing the android showcase I went into this error and the app couldn't be started without setting the following property:

```
System.setProperty("vertx.disableFileCPResolving", "true")
```

without setting the property an exception is thrown when using an sdk-service that initializes a vertx client.

if possible we need to ensure that the vertx folder is not created by default so that android developers don't run into that issue

**Comment by mitch-lbw** [comment]
https://vertx.io/docs/vertx-core/java/#_configuring_vert_x_cache

**Comment by marc0olo** [comment]
I think its necessary to use the cache. we should provide instructions how to change the location and how to use it with android

**Comment by marc0olo** [comment]
will be probably be obsolet when we address #174
