### ISSUE TITLE
For more security spongycastle -> bouncycastle

### ISSUE THREAD

**Issue by Neustradamus** [kryptokrauts/aepp-sdk-java#124]
For more security, can you change old spongycastle (based on old bouncycastle) to bouncycastle?
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncy%20castle
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncycastle
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by marc0olo** [comment]
in general we used version `1.61` bouncycastle in the sdk. maybe at some places we accidentially used spongycastle classes that are included in other dependencies.

I will check that and replace those classes with the bouncycastle classes. additionally we will update to version `1.65` then

**Comment by marc0olo** [comment]
@Neustradamus I found the usage of Spongycastle only in the following two classes:
- `KeyPairServiceFactoryTest`
- `KeyPairServiceTest`

have you found another place where it is used?

**Comment by Neustradamus** [comment]
@marc0olo: I have done this search :)
- https://github.com/kryptokrauts/aepp-sdk-java/search?q=spongycastle&unscoped_q=spongycastle
