### ISSUE TITLE
Dynamic creation of enums VirtualMachine & Network (preparation for Iris harfork)

### ISSUE THREAD

**Issue by marc0olo** [kryptokrauts/aepp-sdk-java#127]
in order to make contract related transactions work with the upcoming iris hardfork we need to specify the correct VM version.

maybe we should introduce another variable which allows us to select the correct VM version based on the hardfork. but I don't think this is necessary as we always support the most recent version with new sdk releases.

**Comment by marc0olo** [comment]
https://github.com/aeternity/aeternity/blob/master/apps/aecontract/include/aecontract.hrl

**Comment by marc0olo** [comment]
VM version:
- 6 for AEVM
- 7 for FATE

ABI Version => no changes

**Comment by marc0olo** [comment]
as discussed we want to allow dynamic creating of the `VirtualMachine` enum that enables users to define custom ABI and VM versions

**Comment by mitch-lbw** [comment]
added to Methods to dynamically change the ABI and VM versions, based on a VM:
VirtualMachine.FATE
.withVmVersion(BigInteger.valueOf(7)
.withAbiVersion(BigInteger.valueOf(3)

**Comment by marc0olo** [comment]
we should set the default of FATE vm version back to 5 so that we can make a new release
