### ISSUE TITLE
revisit KeyPair handling and attribute naming

### ISSUE THREAD

**Issue by marc0olo** [kryptokrauts/aepp-sdk-java#128]
the wording here can be confusing as the actual **address** of an account is currently referenced as **publicKey** of the basekeypair.

maybe we should discard the keypair classes and introduce account classes

we should also keep #47 in mind here

**Comment by mitch-lbw** [comment]
- BasekeyPair ist renamed to Account and does not implement KeyPair Interface anymore
- PublicKey attribute is renamed to account to reflect its purpose/intention

**Comment by marc0olo** [comment]
see discussion in #144. currently I think Account is even more confusing and not correct. I think we should get rid of `RawKeyPair` and `BaseKeyPair` and just provide a single class `KeyPair` that can return the private and public keys as bytearray or base58encoded.

we should also think about keeping the HD hierarchy using the mnemonic separate to the `KeyPair` implementation and instead allow to easily return one or multiple `KeyPair`s by providing the index(s). this might also be part of the KeyPairService. wherever it fits best.

what's your take on that, @mitch-lbw ?
