### ISSUE TITLE
use the new external endpoint for dry-run actions

### ISSUE THREAD

**Issue by marc0olo** [kryptokrauts/aepp-sdk-java#129]
as long there is no specific requirement/demand we will force the user to connect to a node that has the debug-endpoint enabled. otherwise it won't be possible to create contract related transactions.

dryRun can only be executed when the debug-endpoint is enabled and allows to:
- calculate the required gas fee
- make sure that the tx throws no errors

when the debug-endpoint is not enabled we throw a proper exception when trying to create contract related transactions.

**Comment by marc0olo** [comment]
maybe we can introduce another way to estimate gas and gasprice:
- https://forum.aeternity.com/t/calculate-gas-and-gasprice-without-using-dry-run/7486

we should check if debug-endpoint is active when initializing the aeternity service

**Comment by marc0olo** [comment]
we can also leave it like it is and just document that the dry-run functionality requires the debug endpoint.

for the generated classes of our plugin we would need to make some changes that check for the error and throw a meaningful exception.

what do you think @mitch-lbw

**Comment by marc0olo** [comment]
since `v6.0.0-rc3` there exists a new external endpoint to perform dry-run actions, see release notes:
- https://github.com/aeternity/aeternity/blob/v6.0.0-rc3/docs/release-notes/RELEASE-NOTES-6.0.0-rc3.md

we should consider that this endpoint is by default limited to 6.000.000 gas. this can be configured by the node. the debug endpoint will always allow unlimited gas usage but isn't intended to be used for common actions.

what do you think @mitch-lbw? maybe we should add a configuration param to switch between debug endpoint and external endpoint

**Comment by marc0olo** [comment]
I started implementing this but somehow always receive a 404 for the new endpoint. trying to clarify this before we further proceed here.

**Comment by mitch-lbw** [comment]
Yes i prefer the solution providing a configuration switch whether to use the debug or external endpoint

**Comment by marc0olo** [comment]
I opened an issue regarding the new endpoint -> https://github.com/aeternity/aeternity/issues/3635

**Comment by marc0olo** [comment]
closed with #159
