### ISSUE TITLE
consider new config param for dry-run calls

### ISSUE THREAD

**Issue by marc0olo** [kryptokrauts/aepp-sdk-java#173]
I am not sure how this is currently implemented right now as I never considered this relevant until now. for the background about this issue see https://github.com/kryptokrauts/contraect-maven-plugin/issues/66

**Comment by marc0olo** [comment]
by activating this config param we could automatically use the zero address account for every dry-run.

see https://github.com/kryptokrauts/contraect-maven-plugin/issues/66#issuecomment-879869538

**Comment by mitch-lbw** [comment]
@marc0olo - actually i would prefer using the zero address account when calling dry-runs. I also would introduce a parameter switch to the sdk (use zero address account, default: true) as well as the zero address account as additional param in case the behaviour might switch in the future. The change will be made within the sdk and i will remove setting the key within the plugin

**Comment by marc0olo** [comment]
sounds good to me
