### ISSUE TITLE
provide helper methods for transactions

### ISSUE THREAD

**Issue by mitch-lbw** [kryptokrauts/aepp-sdk-java#34]
- provide a smoother way to generate, sign and post transactions
   - get next nonce for account
   - methods-chains, ...
- provide possibility to decode and encode calldata for more convience when dealing with contracts

**Comment by mitch-lbw** [comment]
implemented builder way to create and post transactions
added get next nonce for account

**Comment by marc0olo** [comment]
@mitch-lbw what is the current state here? do you think we still have this task open? or should we identify new helper methods in another issue on requests?

**Comment by mitch-lbw** [comment]
Most of the methods related to this ticket are done. I close this one and we'll open new tickets on demand for specific functions as you proposed
