### ISSUE TITLE
refactoring of the TransactionFactory and Services/ApiClients

### ISSUE THREAD

**Issue by marc0olo** [kryptokrauts/aepp-sdk-java#44]
- [x] provide methods with predefined default values where it makes sense
  - devs shouldn't always need to provide all parameters
  - we have built a wrapper around the builder-methods but in fact we want to provide the builder for the developers
- [x] check `@NonNull` attributes of all Transaction types (e.g. payload for SpendTransaction shouldn't be required)
- [x] consider #48 for the design after refactoring

**Comment by marc0olo** [comment]
I think we should mark the `TransactionFactory` deprecated and provide default values for the required fields and let the developers directly access the builder of each transaction type.

The open question then is how to perform the `createInternal` method for the debugApi which currently requires an initialized ApiClient for each transaction type.

**Comment by marc0olo** [comment]
@mitch-lbw we should also think about a way to get access to all ApiClients with a certain configuration as this shouldn't be provided by the TransactionService.

currently we e.g. define a `ChainService` and an `AccountService` just to get access to the methods provided by the ApiClients

**Comment by mitch-lbw** [comment]
Yes - as discussed - we would not recommend to expose generated ApiClients because the underlying AE protocol is currently not stable atm. Furthermore we want provide an SDK which aims to realize a reliable API.

**Comment by marc0olo** [comment]
please consider #48 for the design after refactoring:
- https://github.com/kryptokrauts/aepp-sdk-java/commit/4c28dd0190b5474f034555a4fb756f3b37a7ea9a

maybe this can also be made more generic. a look into the python sdk might help:
- https://github.com/aeternity/aepp-sdk-python/blob/develop/aeternity/transactions.py

**Comment by marc0olo** [comment]
#48 won't be included in this refactoring.
