### ISSUE TITLE
HD wallet support (BIP44, BIP32 + BIP39)

### ISSUE THREAD

**Issue by marc0olo** [kryptokrauts/aepp-sdk-java#6]
We want to provide HD wallet support.

**Sources**
- [BIP32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki)
- [BIP44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki)
    - [Registered coin types for BIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md)
- [BIP39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki)

![image](https://user-images.githubusercontent.com/8124114/53304313-099a9c00-3874-11e9-9fcd-75df4150202a.png)

**Example Implementation (Javascript)**
- https://github.com/aeternity/hd-wallet-js
- https://github.com/airgap-it/airgap-coin-lib/blob/master/lib/protocols/aeternity/AEProtocol.ts

**Comment by mitch-lbw** [comment]
Added mnemonic seed word list support for creating keyPairs

**Comment by mitch-lbw** [comment]
chain code for aeternity has to be applied for hd wallet generation
