### ISSUE TITLE
refactoring for dryRun actions

### ISSUE THREAD

**Issue by marc0olo** [kryptokrauts/aepp-sdk-java#63]
there were some changes regarding the dryRun and now we have new generated model-classes with more possibilites than in the past.

the "old-style" is still working. but we probably need some small refactoring here.

**Comment by mitch-lbw** [comment]
especially the gasPrice cannot be taken from the dryRun and should be manually set by the users of the SDK - this has to be documented

**Comment by marc0olo** [comment]
closing this. the documentation will be done in #35
